services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
    command: bash -c "cd backend && alembic upgrade head && cd .. && uvicorn backend.main:app --host 0.0.0.0 --port 80"
    volumes:
      - .:/data
    depends_on:
      - db
      - redis
    networks:
      - app-net

  db:
    image: postgres:13

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: reddit_clone_db

    ports:
      - "5432:5432"

    volumes:
      - pg-data:/var/lib/postgresql/data

    networks:
      - app-net

  redis:
    image: redis/redis-stack

    ports:
     - "6379:6379"

    networks:
     - app-net

volumes:
  pg-data:

networks:
  app-net:
    driver: bridge