"""add reactions to post

Revision ID: 69c0568493b8
Revises: 4c28e5da331b
Create Date: 2024-12-24 14:39:25.835816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69c0568493b8'
down_revision: Union[str, None] = '4c28e5da331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reactions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'reactions')
    # ### end Alembic commands ###
